services:
  mariadb:
    build:
      context: ./requirements/mariadb
    container_name: mariadb
    restart: always
    environment:
      SQL_DATABASE: ${SQL_DATABASE}
      SQL_USER: ${SQL_USER}
    secrets:
      - db_password
      - db_root_password
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${SQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  wordpress:
    depends_on:
      mariadb:
        condition: service_healthy
    build:
      context: ./requirements/wordpress
      args:
        WP_VERSION: ${WP_VERSION:-6.8.1}
    container_name: wordpress
    restart: always
    environment:
      SQL_DATABASE: ${SQL_DATABASE}
      SQL_USER: ${SQL_USER}
      SQL_HOST: mariadb
      WP_TITLE: ${WP_TITLE}
      WP_URL: ${WP_URL}
    secrets:
      - db_password
      - credentials
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception
    healthcheck:
      test: ["CMD-SHELL", "pidof php-fpm7.4 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  nginx:
    depends_on:
      wordpress:
        condition: service_healthy
    build:
      context: ./requirements/nginx
      no_cache: true
      args:
        LOGIN: ${LOGIN:-}
    container_name: nginx
    restart: always
    environment:
      LOGIN: ${LOGIN:-}
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception
    healthcheck:
      test: ["CMD-SHELL", "curl -kf https://localhost:443 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  mariadb_data:
    name: mariadb_data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/mariadb
  wordpress_data:
    name: wordpress_data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/wordpress

networks:
  inception:
    name: inception

secrets:
  db_password:
    file: ../secrets/db_password.txt
  db_root_password:
    file: ../secrets/db_root_password.txt
  credentials:
    file: ../secrets/credentials.txt
